#ifndef __BUILD_MODE_H__
#define __BUILD_MODE_H__


#undef  ENABLE_CRT_MEMORY_CHECKS
#undef  ENABLE_INLINE
#define ENABLE_PRINT_FUNCTIONS
#define ENABLE_SERVER_PRINT_FUNCTIONS
#define ENABLE_ASSERTS_IN_DEBUG
#define ENABLE_ASSERTS_IN_RELEASE
#define ENABLE_ASSERT_BREAKS
#define ENABLE_COMMAND_LINE_INPUT


#endif
